### PR TITLE
upgrade to rc2, add embedded resources, fix test/dnx run/dnx web

### LINKED ISSUE #18: Build broke
Error message from CI:

```
System.InvalidCastException: Unable to cast object of type 'FSharp.Dnx.FSharpProjectCompiler' to type 'Microsoft.Dnx.Compilation.IProjectCompiler'.
```

Probably just another DNX refactoring (renaming of classes/namespaces).

### PR DESCRIPTION
**Pull request by enricosada**
fix #18 , #15, #9 
- use Microsoft.Extensions.Compilation instead of Microsoft.Dnx.Compilation
- pin sdk version
- pin FSharp.Dnx version to dnx 1.0.0-rc2
- fix dnx451 deps
- use xnunit dnx runner
- add doc
- add tests without FSharp.Dnx
- log compiler arguments with debug build
- fix resolve FSharp.Core.resources
  ResolveHooker.HandleResolve should consider only FSharp.Core, but there was
  a bug with FSharp.Core.resources with assembly name
  
  FSharp.Core.resources, Version=4.4.0.0, Culture=it-IT, PublicKeyToken=b03f5f7f11d50a3a
- fix dnx run
- add all directory with project.json to global.json
- add support for embedded resources
- use embedded resources instead of a separated mvc views project
- add docs

[Review on Reviewable](https://reviewable.io/reviews/fsprojects/fsharp-dnx/24)

### CODE REVIEW

**Comment by Alxandr** [comment]
First of all. This (in general) seems great. There are a lot of great things here. Especially the fact that you've added support for embedded references. Really great stuff.

Some points:
- master should not be bound to a specific version of  version of DNX or the libraries. It should work against latest. It's built daily and published to myget (much like the unstable sources for DNX itself).
- what's the point of `FSharp.Dnx.UnitTests`? It's written in C# as far as I can tell.

---

Reviewed 36 of 36 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

_[docs/development.md, line 10 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/24#-K5bEjCa4OLYEhMSO2xb:-K5bEjCb2_F3UEQ7F-yL:-494673018) ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/28dcb8f3b31f76cbbecac97eb88b89c5f825fb40/docs/development.md#L10)):_
dnvm upgrade -u

---

_[global.json, line 3 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/24#-K5bFFtb3ofkyxBu8TP1:-K5bFFtcMnVcDld4meTO:1392734111) ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/28dcb8f3b31f76cbbecac97eb88b89c5f825fb40/global.json#L3)):_
Neither sample nor test should be listed in projects. Projects is to enable lookup of projects based on name. We do not want `src` projects to be able to reference `test` projects for instance.

SDK version should not be locked in.

---

_[NuGet.Config, line 8 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/24#-K5bFZzAJAGFVwdioDcy:-K5bFZzAJAGFVwdioDcz:-1359212668) ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/28dcb8f3b31f76cbbecac97eb88b89c5f825fb40/NuGet.Config#L8)):_
Don't use cidev. It's the same as `aspnetvnext`, just not unit-tested.

---

_[README.md, line 9 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/24#-K5bFjtL9nkU_sAQEC2-:-K5bFjtL9nkU_sAQEC20:-755755865) ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/28dcb8f3b31f76cbbecac97eb88b89c5f825fb40/README.md#L9)):_
`master` is not pinned. Release commits are.

---

_[README.md, line 39 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/24#-K5bFrqgb7d8JGMwWbHd:-K5bFrqgb7d8JGMwWbHe:1403423017) ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/28dcb8f3b31f76cbbecac97eb88b89c5f825fb40/README.md#L39)):_
You don't need to build before you test. `dnx test` is enough.

---

_[README.md, line 48 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/24#-K5bFvvWJrDOI2tNyr4Z:-K5bFvvWJrDOI2tNyr4_:2115044766) ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/28dcb8f3b31f76cbbecac97eb88b89c5f825fb40/README.md#L48)):_
Same here as with tests. No need to build first.

---

_[README.md, line 63 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/24#-K5bFzAImFDdZYe0TPJ-:-K5bFzAImFDdZYe0TPJ0:-746340607) ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/28dcb8f3b31f76cbbecac97eb88b89c5f825fb40/README.md#L63)):_
Same here, no need to build.

---

_[sample/HelloFSharp/project.json, line 7 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/24#-K5bGBR_PaSjXDzI9VO1:-K5bGBR_PaSjXDzI9VO2:-180636920) ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/28dcb8f3b31f76cbbecac97eb88b89c5f825fb40/sample/HelloFSharp/project.json#L7)):_
Where did you get this from? Never seen it before.

---

_[sample/HelloFSharp/project.json, line 10 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/24#-K5bGEWG9AZpR2CmQuN_:-K5bGEWG9AZpR2CmQuNa:2076857020) ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/28dcb8f3b31f76cbbecac97eb88b89c5f825fb40/sample/HelloFSharp/project.json#L10)):_
This would simply allow you to run `dnx HelloFSharp` instead of `dnx run`. What's the point of that?

---

_[src/FSharp.Dnx/FileWriteTimeCacheDependency.cs, line 7 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/24#-K5bJIbQOxhPyRGtQ7fL:-K5bJIbQOxhPyRGtQ7fM:896501843) ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/28dcb8f3b31f76cbbecac97eb88b89c5f825fb40/src/FSharp.Dnx/FileWriteTimeCacheDependency.cs#L7)):_
Where is this used? What's it used for? I probably just missed it skimming through the code :).

---

_[src/FSharp.Dnx/project.json, line 8 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/24#-K5bI6gJ2Ym8GZrTl3qX:-K5bI6gJ2Ym8GZrTl3qY:1256722763) ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/28dcb8f3b31f76cbbecac97eb88b89c5f825fb40/src/FSharp.Dnx/project.json#L8)):_
Do not tie down to `rc2`

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/24#-:-K5bEQfvnDhFbXtRif8a:-130453506)_

**Comment by enricosada** [comment]
sry @Alxandr , i wrote the comments in https://reviewable.io but now require write permission to my repo to publish it, and i dont want to do that.

As a personal note (my feedback, i dont want to change your workflow), it's nice to track pending review, but ihmo it doesnt add a lot
It has some pro, unique email for multiple notification, dashboard, for you what is the killer feature? I I am trying to evaluate the tool atm, if you have 2 min for a feedback as user :smile: 

Cons:
- github remove obsolete comments if add a commit on same line ( resolved review )
- ui has issue on mobile ( for example doesnt work right on my iphone chrome/safari )
- less linking inside github ( comments etc )
- pending review/status can be done with label in github

# I'll write there my comments

> docs/development.md, line 10 [r1](raw file):
> dnvm upgrade -u

ok

> global.json, line 3 [r1](raw file):
> Neither sample nor test should be listed in projects. Projects is to enable lookup of projects based on name. We do not want src projects to be able to reference test projects for instance.
> 
> SDK version should not be locked in.

ok for samples/tests

global.json sdk is used by visual studio, it's the minimum required to run. this branch require rc2 at least.
I'll remove for now, and add a note in readme to manually set sdk

> NuGet.Config, line 8 [r1](raw file):
> Don't use cidev. It's the same as aspnetvnext, just not unit-tested.

ok, i'll remove it

> README.md, line 9 [r1](raw file):
> master is not pinned. Release commits are.

i'll write something like `This project's branchs are expected to work with different version of aspnet/dnx`

> README.md, line 39 [r1](raw file):
> You don't need to build before you test. dnx test is enough.
> README.md, line 48 [r1](raw file):
> Same here as with tests. No need to build first.
> README.md, line 63 [r1](raw file):
> Same here, no need to build.

i think is good to show how to  build and after run.
But np, i'll remove it

> sample/HelloFSharp/project.json, line 7 [r1](raw file):
> Where did you get this from? Never seen it before.

new from rc1, see http://stackoverflow.com/questions/33888632/what-does-compilationoptions-emitentrypoint-mean

mean compile as console app instead of library

> sample/HelloFSharp/project.json, line 10 [r1](raw file):
> This would simply allow you to run dnx HelloFSharp instead of dnx run. What's the point of that?

because with this one, i can Debug -> Start in visual studio. 
Without i get the following error



Doesnt work anyway (design time something, i'll add an issue

```
System.NotSupportedException: Specificato metodo non supportato.
   in Microsoft.Dnx.Compilation.DesignTime.DesignTimeProjectReference.EmitAssemb
ly(String outputPath)
   in FSharp.Dnx.FSharpCompiler.CompileProject(CompilationProjectContext project
Context, IEnumerable`1 incomingReferences, IEnumerable`1 incomingSourceReference
s, Func`1 resourcesResolver) in D:\github\fsharp-dnx\src\FSharp.Dnx\FSharpCompil
er.cs:riga 109
```

i think `DesignTimeProjectReference` should be extended too, i'll check

> src/FSharp.Dnx/FileWriteTimeCacheDependency.cs, line 7 [r1](raw file):
> Where is this used? What's it used for? I probably just missed it skimming through the code :).

i was trying to remove `Microsoft.Dnx.Runtime.Sources` dependency, next pr.
i'll remove this file

> src/FSharp.Dnx/project.json, line 8 [r1](raw file):
> Do not tie down to rc2

the minimum version required is rc2, with rc1 doesnt work. 
Should i ignore that and leave like before? I can try to leave previous version

**Comment by enricosada** [comment]
btw @Alxandr you have time for a chat? slack/skype
i want to help, if you have time so i can understand better the problems, what's next todo

**Comment by enricosada** [comment]
> what's the point of FSharp.Dnx.UnitTests? It's written in C# as far as I can tell.

It's to check if xnunit works, and make it easier to add unit tests of c# code.
If FSharp.Dnx doesnt work, tests cannot be run, and is difficult to know why
I added two tests but i removed them from this pr, to minimize diff. This pr was already large enough for a first pr, i need to understand this repo better, and this add rc2, fix, embedded res

**Comment by enricosada** [comment]
ok understood visual studio, sry i am newbie of dnx

```
dnvm upgrade -u
```

upgrade dnvm version to unstable, and **change `default` alias** globally, adding to `PATH` env var of user.

In Visual studio and VSCode, if the global.json sdk property is not set, the `default` alias is used as fallback.
But that mean we change a global config. 
It's ok, but i'll document that, because if someone ( like me ) is new to dnx or this repo, get strange errors and after that, other vs solutions got issues

maybe there is a way like

```
dnvm install latest -a latest-unstable # with ci feed, latest should be rc2
dnvm use latest-unstable
```

and set unstable in global.json

just writing down ideas

**Comment by Alxandr** [comment]
I'm available at skype (AlxandrHeintz).

With regards to `upgrade`, that is indeed a combination of `install`, `use` and setting the default alias, it's just what I've always used :). The problem with not doing `upgrade` (afaik) is that there is no `latest` aliasing. At least there wasn't before. So you had to install latest, then do `use <insert-long-and-painfull-version-string-here>`, which was not fun. Thus `upgrade` was a lot easier. Still not sure I understood the point of the added unit-tests, and I can also discuss the use of reviewable, though don't think this is the right place for it. But it's provided me a good few boons, mainly in the aspect that it somewhat forces me to look through all the files that's changed, and also acknowledge any comments that are made. It doesn't allow me to oversee anything (at least not as easily).

The fact that you need to add commands is new. Also, in dnx, the reason why build before run is useless, is because if you do `build` than `run`, the built code isn't used at all. It still builds it in-memory before running (unless it's changed really recently). So the building becomes an extra action that serves virtually no purpose at all. It does not even speed up launching.

**Comment by Alxandr** [comment]
Oh, and the `"emitEntryPoint": true` should probably be handled by the `FSharpCompiler` (or similar), so that if you have it set to true, and no main method is provided, it fails the compilation (compilation flag that says it's an executable instead of library).

**Comment by enricosada** [comment]
Thx @Alxandr i'll add you in skype

yes, emitEntrypoint is another thing i want to add, now run doesnt work in visual studio ( because of missing entry point , i need to check that too, i'll open an issue after this is merged if is correct to use it )

About install, we can use `latest` argument, and add `-alias something`

```
D:\github\fsharp-dnx>dnvm install latest -u -alias latest-unstable
Determining latest version
'dnx-clr-win-x86.1.0.0-rc2-16312' is already installed in C:\Users\E.SADA\.dnx\r
untimes\dnx-clr-win-x86.1.0.0-rc2-16312.
Adding C:\Users\E.SADA\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-16312\bin to proc
ess PATH
Setting alias 'latest-unstable' to 'dnx-clr-win-x86.1.0.0-rc2-16312'
```

creating a latest-stable

```
D:\github\fsharp-dnx>dnvm install latest -alias latest-stable
Determining latest version
'dnx-clr-win-x86.1.0.0-rc1-update1' is already installed in C:\Users\E.SADA\.dnx
\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1.
Adding C:\Users\E.SADA\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin to pr
ocess PATH
Setting alias 'latest-stable' to 'dnx-clr-win-x86.1.0.0-rc1-update1'
```

**Comment by enricosada** [comment]
Sry if i continue this, it's only a feedback as new user, i got errors in visual studio because `default` alias was `rc1` ( this branch require `rc2` ) and vice versa.
So i was trying to find a way to have a clone -> run experience without change `default` alias ( because that mess global config, and if someone like me is new to dnvm, is a issue ).
I'll add documentation to `upgrade -u` i think is enough

**Comment by enricosada** [comment]
ok done

**Comment by Alxandr** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/24)_

**Pull request merged**
