### PR TITLE
Fixed build

### PR DESCRIPTION
**Pull request by Alxandr**
Removed filewatcher which has been removed from DNX.

### CODE REVIEW

**Comment by raymens** [comment]
Should the file `.vs/config/applicationhost.config` really be in here? IIRC the .vs folder shouldn't be source controlled

**Comment by Alxandr** [comment]
@raymens I considered the same thing. But then I thought that if you end up with examples where you can do "F5" in VS and get a website running it would be nice to be able to tell them what url to navigate to (`localhost:<port>`), where port would be equal for all. Still, I'm not entirely sure.

Generally, I'm for checking in some config into source control, like formatting options and such, to make sure everyone are using the same, though whether or not this one applies I'm unsure of. For now at least it's checked in. It can be removed later if it's agreed that it's a bad idea to leave in the source control (like, if people need to make changes to it locally).

**Comment by raymens** [comment]
F5 auto opens the correct URL right?

I understand why you'd might want that file, just wanted to make sure it didn't sneak itself in by accident :)

**Comment by Alxandr** [comment]
@raymens True. Also, F5 blows up in visual studio atm :P. And it seems there is nothing I can do about it. But, oh, well.

**Pull request merged**
