### PR TITLE
Rc1

### PR DESCRIPTION
**Pull request by jbfp**
[Review on Reviewable](https://reviewable.io/reviews/fsprojects/fsharp-dnx/20)

### CODE REVIEW

**Comment by Alxandr** [comment]
Oo. I was just going to start working on this :) (then, I had 12+ hrs workdays of Android Apps + Connect streaming xD).

**Comment by jbfp** [comment]
:)

I tried removing the aspnet vnext NuGet source (so only the stable rc1-final packages would be downloaded) but of course KoreBuild relies on dev versions

**Comment by Alxandr** [comment]
Reviewed 8 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

_[global.json, line 2 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/20#-K3WkBQrHfFO-uYeVK-2:-K3WkBQrHfFO-uYeVK-3:-421405801) ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/c2c62de8913877feb16441a831ab3a63cb4c4f79/global.json#L2)):_
Unless the behavior's changed in DNX, only `"src"` should be here.

---

_[NuGet.Config, line 4 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/20#-K3WkUnoHLIXI51w9jK1:-K3WkUnoHLIXI51w9jK2:650627350) ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/0270d0b057e2f9ccde5c72131b094cd941e03330/NuGet.Config#L4)):_
It's on purpose I don't allow sources configured on the local machine to interact with the build. It can lead to situations where it builds locally because you've configured some NuGet source that isn't configured on the CI.

---

_[NuGet.Config, line 6 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/20#-K3Wl3EXpjmYh1WDHAHG:-K3Wl3EXpjmYh1WDHAHH:-2021090476) ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/c2c62de8913877feb16441a831ab3a63cb4c4f79/NuGet.Config#L6)):_
Make sure there is a newline at the end of the file.

---

_[src/FSharp.Dnx/Logger.cs, line 33 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/20#-K3Wl6aDadahGO2QK_Cu:-K3Wl6aDadahGO2QK_Cv:-2021090476) ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/c2c62de8913877feb16441a831ab3a63cb4c4f79/src/FSharp.Dnx/Logger.cs#L33)):_
Make sure there is a newline at the end of the file.

---

_[src/FSharp.Dnx/project.json, line 13 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/20#-K3WlGSHq9BH3AjbfbPf:-K3WlGSHq9BH3AjbfbPg:-271695029) ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/0270d0b057e2f9ccde5c72131b094cd941e03330/src/FSharp.Dnx/project.json#L13)):_
Is this package gone, or did you just remove it?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/20)_

**Comment by jbfp** [comment]
Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/FSharp.Dnx/project.json, line 13 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/20#-K3WlGSHq9BH3AjbfbPf:-K3WlyyVoTTd05wm_Ivo:349195579) ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/0270d0b057e2f9ccde5c72131b094cd941e03330/src/FSharp.Dnx/project.json#L13)):_
Well, it's not on the nuget.org feed, it's on the "dev" feed, but now that the "dev" feed has been added again, I guess there's not reason to remove the runtime sources (and then the Logger class and OS check can just be removed)

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/20)_

**Comment by Alxandr** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_[NuGet.Config, line 5 [r3]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/20#-K3WnYt0QJ4vH7CVlFzJ:-K3WnYt0QJ4vH7CVlFzK:167166342) ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/201dff83d0a6036431821aa482d891b14b3f6ff6/NuGet.Config#L5)):_
Correct me if I'm wrong, but I think `aspnetcidev` is the untested feed (ie. stuff there might not even compile properly against each other at times), whereas `aspnetvnext` is guaranteed to have passed unit tests at least. It's not the biggest safety in the world, but I at least feel it's better than `aspnetcidev` (unless I'm mixing up which one is which).

Also, since you've added back the `<clear />`, you need to re-add the nuget.org one too. After all, you're trying to get the release packages from there :P. I think if you just add it before the dev feed, it'll prioritize the nuget.org feed.

---

_[src/FSharp.Dnx/project.json, line 13 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/20#-K3WlGSHq9BH3AjbfbPf:-K3WoH22PvwbcB0vXXSq:-1653824554) ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/0270d0b057e2f9ccde5c72131b094cd941e03330/src/FSharp.Dnx/project.json#L13)):_
There is no reason to remove anything that has `"type": "build"`, even if it's in the dev feed. Because it's compiled in and not referenced. Also guessing this might mean you can change back to the `IsMono` test, which is imho better, as it's not a magic string (on our side at least).

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/20)_

**Comment by Alxandr** [comment]
Looks good. Any way you can re-target the PR against a new branch? Instead of sending it against `master`? Or do I maybe have to create said branch first?

---

Reviewed 3 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/20#-:-K3Wpjz1Mzb1cqS1Gn8h:449800639)_

**Comment by jbfp** [comment]
Oh right, it should've been to an rc1 branch, I'll see what I can do

**Comment by Alxandr** [comment]
I'd like to be against a `release` branch. We'll just tag it as `rc1`.

**Comment by jbfp** [comment]
Googling tells me I have to create a new PR, but you have to create the `release` branch first

**Comment by Alxandr** [comment]
Done. Also, the build failed. Does it run locally for you?

**Comment by jbfp** [comment]
I think the appveyor build fails because it tries to pull rc2 packages that have some namespace changes, i.e. (rc1) Microsoft.Dnx.Compilation.IProjectCompiler -> (rc2) Microsoft.Extensions.CompilationAbstractions.IProjectCompiler

**Comment by Alxandr** [comment]
That might be the case. If you go ahead and make the PR against the `master` branch, I'll go ahead and merge it, and I'll see if I can get it all building and post a release on NuGet.org.

**Pull request closed without merging**
