### PR TITLE
Remove project fsharp json

### PR DESCRIPTION
**Pull request by jbfp**
[Review on Reviewable](https://reviewable.io/reviews/fsprojects/fsharp-dnx/14)

### CODE REVIEW

**Comment by jbfp** [comment]
Related: https://github.com/fsprojects/fsharp-dnx/issues/7

**Comment by Alxandr** [comment]
Thanks a lot for the contribution. I have a few comments, mostly regarding programming style (I try not to use unnecessary keywords) that I've added in the sources. Also, I'm using reviewable.io to review this PR (makes my life easier). A link to the review (so you can see the comments inline with the code) should be generated automatically in the PR somewhere. You'll see a better presentation of the comments there.



---

Review status: 0 of 10 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[src/FSharp.Dnx/CompilationContext.cs, line 9 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/14#-K0jwU-V_nvfwqy0dkiG)** ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/f8b93f7a1a5b90c32c4bbef9d9b895b3b3500507/src/FSharp.Dnx/CompilationContext.cs#L9)):</sup>
Please remove the `private` keyword.



---

<sup>**[src/FSharp.Dnx/FSharpCompiler.cs, line 164 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/14#-K0jx8PO2Xpg9TYMF_kD)** ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/f8b93f7a1a5b90c32c4bbef9d9b895b3b3500507/src/FSharp.Dnx/FSharpCompiler.cs#L164)):</sup>
Please remove `private` keyword.



---

<sup>**[src/FSharp.Dnx/FSharpCompiler.cs, line 176 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/14#-K0jxUdbjovZl_62lbUT)** ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/f8b93f7a1a5b90c32c4bbef9d9b895b3b3500507/src/FSharp.Dnx/FSharpCompiler.cs#L176)):</sup>
At this point, it's not really a F# project configuration (IMHO). Though, in reality, to get to this function, it has to be, not to mention, that `info` will never be `null`, so it's only applicable for anyone running this API directly. Still, I think, simply remove `F#` from this string, so it just states it's not a valid project configuration.



---

<sup>**[src/FSharp.Dnx/FSharpCompiler.cs, line 203 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/14#-K0jy2seMyKeL90ler_4)** ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/f8b93f7a1a5b90c32c4bbef9d9b895b3b3500507/src/FSharp.Dnx/FSharpCompiler.cs#L203)):</sup>
This string needs a `$` in front of it (probably my fault, but I just noticed it).



---

<sup>**[src/FSharp.Dnx/FSharpProjectInfo.cs, line 5 [r1]](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/14#-K0jyL7d_qXIcv9clotY)** ([raw file](https://github.com/fsprojects/fsharp-dnx/blob/f8b93f7a1a5b90c32c4bbef9d9b895b3b3500507/src/FSharp.Dnx/FSharpProjectInfo.cs#L5)):</sup>
For sake of completeness (and introspection), in case anyone ever gets a hold of the `FSharpProjectInfo`, I think `AutoDiscoverFsi` should still be part of it.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/14)

**Comment by Alxandr** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/14)

**Comment by Alxandr** [comment]
Oh, and btw, I'm assuming you'll add a comment if you want me to review again. Mainly because I don't get notified when you add new commits (I just happened to see these). So if you feel you've resolved all issues (which for me it seems you have), just let me know :)

**Comment by jbfp** [comment]
Yeah, I think I've resolved all the issues.
All this pull request and open source stuff is pretty new to me :)

**Comment by Alxandr** [comment]
Yeah, well, leading it is new to me, so we're mostly in the same boat :). Thanks again for your contribution :).



---

Reviewed 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fsprojects/fsharp-dnx/14)

**Comment by jbfp** [comment]
Hehe, no problem, this is a great project :)

**Pull request merged**
