### PR TITLE
Renames YoloDev.Dnx.* to FSharp.Dnx

### PR DESCRIPTION
**Pull request by jbfp**
Regarding https://github.com/fsprojects/fsharp-dnx/issues/8.

There's a reference to a YoloDev.Dnx.Json NuGet but I assume that's another project entirely.

### CODE REVIEW

**Comment by Alxandr** [comment]
First look looks good, though as the repository is just moved CI has not been set up yet. Give me a while to either fix that, or simply validate that everything still works :).

**Comment by Alxandr** [comment]
This currently does not build, but neither does master, and the error is the same, so I'm assuming everything is alright, and merging. Then I'll go try to make it build again.

**Comment by Alxandr** [comment]
Oh, and tanks for the contribution :).

**Comment by jbfp** [comment]
No problem, I'd love to contribute more if needed :)
Regarding the build issues, I had trouble building because of the Microsoft.Dnx.Compilation NuGet package. It built fine when I copied https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Compilation/Caching/FileWriteTimeCacheDependency.cs into the project and removed the dependency

**Comment by Alxandr** [comment]
I'm getting a simple `System.TypeLoadException: Could not load type 'Microsoft.Dnx.Compilation.IFileWatcher'`. Probably something that was moved or removed in DNX.

**Comment by jbfp** [comment]
https://github.com/aspnet/dnx/commit/1a222049e0973ae3971b57d8ea8cffbb9ca34bd0
Yeah looks like it

**Comment by Alxandr** [comment]
@jbfp if you want to stab at another simple issue, take a look at #7. Otherwise I'll probably do it this weekend.

**Comment by jbfp** [comment]
Yeah I'll take a look

**Pull request merged**
